version: "2"
services:

  code:
    image: friofrio_php
    build: .
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - ./:/var/www/html:rw
      - ./.conf/vhost.conf:/etc/apache2/sites-available/000-default.conf:rw

  db:
    image: mariadb
    volumes:
      - /usr/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}